### ISSUE TITLE
Conditions in IF, ELSIF, ASSUME, ASSERT are not coming properly in wpcString if they includes AND, OR, NOT.

### ISSUE THREAD

**Issue by aaalok5106** [NabeelQaiser/BTP_2k18-19#10]

**Comment by NabeelQaiser** [comment]
@aaalok5106 your final green signal is needed here, should I close this issue? As I haven't delve deeper into this issue, hence, can't figure our on my own, whether it is completely solved or not.

**Comment by aaalok5106** [comment]
I worked it out, this issue solved in pr #14 . Please merge it, closing the issue.
