### ISSUE TITLE
Versionise the variable var in "select abcd into var"

### ISSUE THREAD

**Issue by NabeelQaiser** [NabeelQaiser/BTP_2k18-19#11]
The variable should be versionized in SSA form in case of selecting something into a variable

**Comment by aaalok5106** [comment]
@NabeelQaiser , I guess, it will be better if we revise our structure of addressing SELECT statement and consider it in both ways i.e. having INTO and not having INTO.

**Comment by NabeelQaiser** [comment]
@aaalok5106 that sounds great, I was thinking the same too. I'll certainly try it out.

**Comment by NabeelQaiser** [comment]
@aaalok5106 have modified as discussed earlier. You can have a look at it in commit dfd532fe9978c8d6adfbc9460fbd0143776f8dc0  .
Having said that, any corrections/suggestions are welcomed.
