### ISSUE TITLE
Changes requires in my_simulator.py as per latest discussion with Sir.

### ISSUE THREAD

**Issue by imran-iitp** [NabeelQaiser/BTP_2k18-19#15]
Add a new functionality to my_simulator.py which will read a file having database constraints and NULL value of attributes.  Append the constraints into the pl/sql code with assumes and then run the analysis tool  for the verification.

**Comment by aaalok5106** [comment]
@imran-iitp appending  external Constraints without any Conditional construct into the PLSQL code will make it unparsable. What can possibly be done is to store those constraints into some data-structure and it should also be noted that constraints must be in some pre-decided format.

**Comment by NabeelQaiser** [comment]
@imran-iitp it would be good to consider the intermediate CFG to be immutable (supported by the fact that ANTLR parse tree is immutable), thus handling of the constraints (and assumptions for that matter) should be done alongside while generating VCs as @aaalok5106 has mentioned above.

Having said that, any further suggestions are welcomed.

**Comment by imran-iitp** [comment]
@aaalok5106 we can create new DS for handling constraints as well as we can also modify the PLSQL grammar to accommodate new changes. Apply any method which is suitable as per our specifications. 

@NabeelQaiser First try to read the file which contains NULL information about DB attributes and constraints of DB Applications . Second, Append these information into the PLSQL code at appropriate positions before passing to ANTLR parser.

**Comment by imran-iitp** [comment]
Does our tool handle nested IF-ELSE without ELSE statement in the program. For example consider  salary.txt code.
[salary.txt](https://github.com/NabeelQaiser/BTP_2k18-19/files/2860550/salary.txt)
860534/salary.txt)

**Comment by imran-iitp** [comment]
I think current implementation misses the last ELIF expression while generating rawcfg. Check it with attached code.

**Comment by aaalok5106** [comment]
> I think current implementation misses the last ELIF expression while generating rawcfg. Check it with attached code.

Solved in #2

**Comment by NabeelQaiser** [comment]
issue taken care in fc4725c429e50baf0e4d3a5f08d530a0016b094b
