### ISSUE TITLE
Missing "else" block after "elseif" block in raw CFG

### ISSUE THREAD

**Issue by NabeelQaiser** [NabeelQaiser/BTP_2k18-19#2]
@aaalok5106  The "else" block is not been included in the raw CFG , in case , if there is no "else" block after "elseif" statement.

**Comment by aaalok5106** [comment]
Thanks for notifying the issue, I'm working on it.

**Comment by aaalok5106** [comment]
Issue #2 solved, sent a pr, please merge it.

**Comment by aaalok5106** [comment]
and that pr is #5

**Comment by NabeelQaiser** [comment]
@aaalok5106 thank for sparing your time on it. BTW, it looks good now. Cheers.
