### ISSUE TITLE
Constraints in sepcification file.

### ISSUE THREAD

**Issue by imran-iitp** [NabeelQaiser/BTP_2k18-19#23]
Instead of writing only constraints in the specification file and using it for  assume as well as assert  , better we need to write assume and assert separately in specification file itself and place assume constraints at place of assume (in the beginning)  in plsql code and assert constraint at place of assert ( at the end) in plsql code. This is important because some time we may give different constraint for assume and assert.
for example in case of DELETE operation, assume and assert expression will be different.

Existing implementation uses same constraint for assume as well as assert, which may be not true for DELETE operation. So, in specification file,  write assume and assert at place of constraints and do the required modification in preprocessing.py to accommodate these changes.

**Comment by NabeelQaiser** [comment]
solved in 2a70cd6cc039690d3b1ce383982bcfc381bc1595
